### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by Navyguy330** [enjoy2000/discord-pokemon-go-snipe-bot#2]
File "C:\Users\Adam\Desktop\Snipe-bot-Antispam\bot.py", line 21
    async def on_ready():
        ^
SyntaxError: invalid syntax

**Comment by Navyguy330** [comment]
python3 is giving my syntax error, using python bot.py just gives more errors?

**Comment by enjoy2000** [comment]
You need `Python 3.4.2+`

**Comment by Navyguy330** [comment]
I installed it lol

**Comment by Navyguy330** [comment]
I have C:\Users\Adam>python
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:01:18) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by Navyguy330** [comment]
http://prntscr.com/bywqc1

**Comment by Navyguy330** [comment]
C:\Users\Adam\Desktop\discord-pokemon-go-snipe-bot-master>python3 bot.py
'python3' is not recognized as an internal or external command,
operable program or batch file.

**Comment by enjoy2000** [comment]
Please install packages in `requirements.txt`
With pip: `pip install -r requirements.txt`
After that, try `python bot.py`

**Comment by Navyguy330** [comment]
I did already intall requirements

**Comment by enjoy2000** [comment]
What errors come next?
Sorry I'm not familiar with python on `window`

**Comment by Navyguy330** [comment]
Traceback (most recent call last):
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\http.py", line 195, in static_login
    data = yield from self.get(self.ME)
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\http.py", line 137, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: UNAUTHORIZED (status code: 401): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bot.py", line 47, in <module>
    client.run(api_key)
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 486, in run
    self.loop.run_until_complete(self.start(*args, **kwargs))
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python35-32\lib\asyncio\base_events.py", line 387, in run_until_complete
    return future.result()
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python35-32\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 457, in start
    yield from self.login(*args, **kwargs)
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 383, in login
    yield from getattr(self, '_login_' + str(n))(*args, **kwargs)
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 314, in _login_1
    yield from self.http.static_login(token, bot=is_bot)
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\http.py", line 199, in static_login
    raise LoginFailure('Improper token has been passed.') from e
discord.errors.LoginFailure: Improper token has been passed.
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x03828F30>

C:\Users\Adam\Desktop\discord-pokemon-go-snipe-bot-master>

**Comment by enjoy2000** [comment]
Your bot is not authorized yet.
Did your follow my instructions on read me? Please have a look again.

**Comment by Navyguy330** [comment]
I did exactly that

**Comment by Navyguy330** [comment]
http://prntscr.com/bywths

**Comment by Navyguy330** [comment]
well it is not letting me authorize no matter what

**Comment by Navyguy330** [comment]
any help wouldbe great I cannot find anything

**Comment by Navyguy330** [comment]
I think it just doesnt work man

**Comment by Navyguy330** [comment]
please man?

**Comment by Navyguy330** [comment]
ive been at this for hours

**Comment by enjoy2000** [comment]
Did u open your Server Settings and Integrate your bot there?

**Comment by Navyguy330** [comment]
it wont show up there no matter how much I auth

**Comment by enjoy2000** [comment]
Sorry for didn't help much!

**Comment by Navyguy330** [comment]
I got it to work
your test config file has teh syntax wrong for the api key  its api_key:  NOT apiKey:

**Comment by Navyguy330** [comment]
god dman that was a bitch lol
