### ISSUE TITLE
Serious error on newest update

### ISSUE THREAD

**Issue by Navyguy330** [enjoy2000/discord-pokemon-go-snipe-bot#23]
C:\discord-pokemon-go-snipe-bot>python bot.py
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\discord\http.py", l
ine 195, in static_login
    data = yield from self.get(self.ME)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\discord\http.py", l
ine 137, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: UNAUTHORIZED (status code: 401): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bot.py", line 135, in <module>
    client.run(api_key)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\discord\client.py",
 line 486, in run
    self.loop.run_until_complete(self.start(*args, **kwargs))
  File "C:\Program Files (x86)\Python35-32\lib\asyncio\base_events.py", line 387
, in run_until_complete
    return future.result()
  File "C:\Program Files (x86)\Python35-32\lib\asyncio\futures.py", line 274, in
 result
    raise self._exception
  File "C:\Program Files (x86)\Python35-32\lib\asyncio\tasks.py", line 239, in _
step
    result = coro.send(None)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\discord\client.py",
 line 457, in start
    yield from self.login(*args, **kwargs)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\discord\client.py",
 line 383, in login
    yield from getattr(self, '_login_' + str(n))(*args, **kwargs)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\discord\client.py",
 line 314, in _login_1
    yield from self.http.static_login(token, bot=is_bot)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\discord\http.py", l
ine 199, in static_login
    raise LoginFailure('Improper token has been passed.') from e
discord.errors.LoginFailure: Improper token has been passed.
Exception ignored in: <bound method ClientSession.__del__ of <aiohttp.client.Cli
entSession object at 0x038B83B0>>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\aiohttp\client.py",
 line 91, in __del__
  File "C:\Program Files (x86)\Python35-32\lib\asyncio\base_events.py", line 117
7, in call_exception_handler
  File "C:\Program Files (x86)\Python35-32\lib\logging\__init__.py", line 1308,
in error
  File "C:\Program Files (x86)\Python35-32\lib\logging\__init__.py", line 1415,
in _log
  File "C:\Program Files (x86)\Python35-32\lib\logging\__init__.py", line 1425,
in handle
  File "C:\Program Files (x86)\Python35-32\lib\logging\__init__.py", line 1487,
in callHandlers
  File "C:\Program Files (x86)\Python35-32\lib\logging\__init__.py", line 855, i
n handle
  File "C:\Program Files (x86)\Python35-32\lib\logging\__init__.py", line 1047,
in emit
  File "C:\Program Files (x86)\Python35-32\lib\logging\__init__.py", line 1037,
in _open
NameError: name 'open' is not defined

C:\discord-pokemon-go-snipe-bot>

**Comment by Navyguy330** [comment]
fixed idk what happened but redid the auth
