### ISSUE TITLE
still getting error

### ISSUE THREAD

**Issue by pogoKA** [enjoy2000/discord-pokemon-go-snipe-bot#37]
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<announcement() done, defined at bot.py:142> exception=SystemExit()>
Traceback (most recent call last):
  File "C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 486, in run
    self.loop.run_until_complete(self.start(_args, *_kwargs))
  File "C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 375, in run_until_complete
    self.run_forever()
  File "C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 345, in run_forever
    self._run_once()
  File "C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 1312, in _run_once
    handle._run()
  File "C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\asyncio\events.py", line 125, in _run
    self._callback(*self._args)
  File "C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "bot.py", line 151, in announcement
    sys.exit()
SystemExit

**Comment by enjoy2000** [comment]
Because u have not configured your announcement message yet.

But I’ve just update, please git pull to update, or config your message in `config.json`

**Comment by pogoKA** [comment]
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<announcement() done, defined at bot.py:246> exception=SystemExit()>
Traceback (most recent call last):
  File "C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 486, in run
    self.loop.run_until_complete(self.start(*args, **kwargs))
  File "C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 375, in run_until_complete
    self.run_forever()
  File "C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 345, in run_forever
    self._run_once()
  File "C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 1312, in _run_once
    handle._run()
  File "C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\asyncio\events.py", line 125, in _run
    self._callback(*self._args)
  File "C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "bot.py", line 255, in announcement
    sys.exit()
SystemExit

**Comment by pogoKA** [comment]
now i update, and run.
and config fill message.

c:>python bot.py
{'delay': 200, 'message': 'pokemon_name lat,long [IV] [extra info]'}
Posting announcements..
Traceback (most recent call last):
  File "C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\http.py", line 195,
in static_login
    data = yield from self.get(self.ME)
  File "C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\http.py", line 137,
in request
    raise HTTPException(r, data)
discord.errors.HTTPException: UNAUTHORIZED (status code: 401): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bot.py", line 278, in <module>
    client.run(api_key)
  File "C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 486
, in run
    self.loop.run_until_complete(self.start(_args, *_kwargs))
  File "C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 387, in run_
until_complete
    return future.result()
  File "C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 457
, in start
    yield from self.login(_args, *_kwargs)
  File "C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 383
, in login
    yield from getattr(self, '_login_' + str(n))(_args, *_kwargs)
  File "C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 314
, in _login_1
    yield from self.http.static_login(token, bot=is_bot)
  File "C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\http.py", line 199,
in static_login
    raise LoginFailure('Improper token has been passed.') from e
discord.errors.LoginFailure: Improper token has been passed.
Exception ignored in: <bound method ClientSession.__del__ of <aiohttp.client.ClientSession object at 0x0000000
00379C908>>
Traceback (most recent call last):
  File "C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\site-packages\aiohttp\client.py", line 91,
 in **del**
  File "C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 1177, in cal
l_exception_handler
  File "C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\logging__init__.py", line 1308, in error
  File "C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\logging__init__.py", line 1415, in _log
  File "C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\logging__init__.py", line 1425, in handle

  File "C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\logging__init__.py", line 1487, in callHa
ndlers
  File "C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\logging__init__.py", line 855, in handle
  File "C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\logging__init__.py", line 1047, in emit
  File "C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\logging__init__.py", line 1037, in _open
NameError: name 'open' is not defined
Exception ignored in: <bound method Task.__del__ of <Task pending coro=<announcement() running at bot.py:257>
wait_for=<Future pending cb=[Task._wakeup()]>>>
Traceback (most recent call last):
  File "C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 92, in **del**
  File "C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 1177, in cal
l_exception_handler
  File "C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\logging__init__.py", line 1308, in error
  File "C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\logging__init__.py", line 1415, in _log
  File "C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\logging__init__.py", line 1425, in handle

  File "C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\logging__init__.py", line 1487, in callHa
ndlers
  File "C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\logging__init__.py", line 855, in handle
  File "C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\logging__init__.py", line 1047, in emit
  File "C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\logging__init__.py", line 1037, in _open
NameError: name 'open' is not defined

c:>

**Comment by enjoy2000** [comment]
Your bot is not authorised yet, please check read me to add your bot to server

**Comment by pogoKA** [comment]
no, i add bot.

http://imgur.com/a/rw34L

**Comment by enjoy2000** [comment]
Check again, your config `api_key` must be `bot token` not app secret or something else

**Comment by pogoKA** [comment]
c:>python bot.py
{'delay': 200, 'message': 'pokemon_name lat,long [IV] [extra info]'}
Posting announcements..
Logged in as
pogoKAbot

---

http://imgur.com/a/OjnLl
http://imgur.com/a/pLetN
10min after still not working.

**Comment by pogoKA** [comment]
this bot can'nt Automatically posting for rare pokemon lat,long ?

**Comment by enjoy2000** [comment]
Yes, u need other one `python bot.py scrawl` or `python bot.py trackemon`

**Comment by pogoKA** [comment]
if i python bot.py trackemon run, Automatically posting for rare pokemon lat,long ?

**Comment by pogoKA** [comment]
http://imgur.com/a/1hII6

not working, i start 10 hours. but bot is dont auto posting.

**Comment by enjoy2000** [comment]
It looks good.

Can you check config `scrawl_channels`, they are the channels that scrawl will send scrawl results to.

**Comment by pogoKA** [comment]
yes,i ceheck done, but same result. trackmon site down ?

**Comment by pogoKA** [comment]
bot rare scrawl speed very slow, how speed up ?

**Comment by pogoKA** [comment]
thansk you, enjoy2000 is good programmer!

bot rare scrawl speed very slow, how speed up ?

http://imgur.com/a/31RZv   i delay fast set. i want  many rara pokemon auto posting 
but http://imgur.com/a/31RZv

**Comment by pogoKA** [comment]
i thought bot need restart option.

i always restart once for 30 minutes because re search pokemon posting scrawl.

**Comment by pogoKA** [comment]
and http://imgur.com/a/JdBXT   why delete ?

**Comment by pogoKA** [comment]
and add please. http://pokemongocheck.com/vision

bot.py scrawl is not work, pokesniper.com is up posting, but discord bot not working.

**Comment by enjoy2000** [comment]
fixed
