### ISSUE TITLE
error no module name requests

### ISSUE THREAD

**Issue by Navyguy330** [enjoy2000/discord-pokemon-go-snipe-bot#38]
C:\Scrawler>python bot.py trackemon
Traceback (most recent call last):
  File "bot.py", line 12, in <module>
    import requests
ImportError: No module named 'requests'

**Comment by enjoy2000** [comment]
pip install again

**Comment by Navyguy330** [comment]
C:\Scrawler>pip install -r requirements.txt
Requirement already satisfied (use --upgrade to upgrade): aiohttp==0.21.6 in c:\
program files (x86)\python35-32\lib\site-packages (from -r requirements.txt (lin
e 1))
Requirement already satisfied (use --upgrade to upgrade): chardet==2.3.0 in c:\p
rogram files (x86)\python35-32\lib\site-packages (from -r requirements.txt (line
 2))
Requirement already satisfied (use --upgrade to upgrade): discord.py==0.10.0 in
c:\program files (x86)\python35-32\lib\site-packages (from -r requirements.txt (
line 3))
Collecting requests==2.10.0 (from -r requirements.txt (line 4))
  Downloading requests-2.10.0-py2.py3-none-any.whl (506kB)
    100% |################################| 512kB 1.3MB/s
Requirement already satisfied (use --upgrade to upgrade): websockets==3.1 in c:\
program files (x86)\python35-32\lib\site-packages (from -r requirements.txt (lin
e 5))
Installing collected packages: requests
Successfully installed requests-2.10.0

C:\Scrawler>python bot.py trackemon
Traceback (most recent call last):
  File "bot.py", line 27, in <module>
    config = json.load(output)
  File "C:\Program Files (x86)\Python35-32\lib\json\__init__.py", line 268, in l
oad
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Program Files (x86)\Python35-32\lib\json\__init__.py", line 319, in l
oads
    return _default_decoder.decode(s)
  File "C:\Program Files (x86)\Python35-32\lib\json\decoder.py", line 339, in de
code
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files (x86)\Python35-32\lib\json\decoder.py", line 355, in ra
w_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 58 column 2 (char 74
8)
Exception ignored in: <bound method ClientSession.__del__ of <aiohttp.client.Cli
entSession object at 0x02CCFD50>>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\aiohttp\client.py",
 line 91, in __del__
  File "C:\Program Files (x86)\Python35-32\lib\asyncio\base_events.py", line 117
7, in call_exception_handler
  File "C:\Program Files (x86)\Python35-32\lib\logging\__init__.py", line 1308,
in error
  File "C:\Program Files (x86)\Python35-32\lib\logging\__init__.py", line 1415,
in _log
  File "C:\Program Files (x86)\Python35-32\lib\logging\__init__.py", line 1425,
in handle
  File "C:\Program Files (x86)\Python35-32\lib\logging\__init__.py", line 1487,
in callHandlers
  File "C:\Program Files (x86)\Python35-32\lib\logging\__init__.py", line 855, i
n handle
  File "C:\Program Files (x86)\Python35-32\lib\logging\__init__.py", line 1047,
in emit
  File "C:\Program Files (x86)\Python35-32\lib\logging\__init__.py", line 1037,
in _open
NameError: name 'open' is not defined

C:\Scrawler>'
''' is not recognized as an internal or external command,
operable program or batch file.

C:\Scrawler>

**Comment by Navyguy330** [comment]
did requirements again now this

**Comment by enjoy2000** [comment]
how other workers? check your config son syntax pls

**Comment by Navyguy330** [comment]
yeah i just did new config seems fine


the list of poekmon under trackemon config is that the only pokemon it will grab?

**Comment by Navyguy330** [comment]
its also not showing the IV or moveset either.

**Comment by Navyguy330** [comment]
Also does it post on demand for trackemon or still use the scrawl delay??

**Comment by enjoy2000** [comment]
Delay, they don’t have IV or move details too.

You will need some bot to encounter it to get that data

**Comment by Navyguy330** [comment]
Oh so not much difference?  Except time left ?  Damn damn lol
