### ISSUE TITLE
Looping with trackemon & other bugs.

### ISSUE THREAD

**Issue by itsDustinBerry** [enjoy2000/discord-pokemon-go-snipe-bot#49]
At the end of the Trackemon list we set in the config, Does it go back through and do a constant loop of said list?

I noticed once it reached the end of mine, It seems to stick there and do nothing else.

I am going to condense all my issues into one issue so i do not make a bunch. I am getting this error sometimes

Also, When is the possiblity of pulling IVs for pokemon?

There is this website that maybe you could add
http://spawns.sebastienvercammen.be/

Also, It seems like sometimes I will lose connection. I don;t have the message long at the moment, but I'll get it to you as soon as it comes back up

This is my message log:

ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<scrawl_trackemon_worker() done, defined at bot.py:174> exception=Exception("Can't retrieve session id for api.",)>
Traceback (most recent call last):
  File "C:\Users\My\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "bot.py", line 194, in scrawl_trackemon_worker
    message = scrawl_trackemon(pokemon_name)
  File "bot.py", line 79, in scrawl_trackemon
    raise Exception('Can\'t retrieve session id for api.')
Exception: Can't retrieve session id for api.
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<scrawl_trackemon_worker() done, defined at bot.py:174> exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)',)>
Traceback (most recent call last):
  File "C:\Users\My\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "bot.py", line 194, in scrawl_trackemon_worker
    message = scrawl_trackemon(pokemon_name)
  File "bot.py", line 85, in scrawl_trackemon
    data = response.json()
  File "C:\Users\My\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\models.py", line 812, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\My\AppData\Local\Programs\Python\Python35-32\lib\json__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\Users\My\AppData\Local\Programs\Python\Python35-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\My\AppData\Local\Programs\Python\Python35-32\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Also, I got a Connection closed code = 1000 - No reason.

**Comment by enjoy2000** [comment]
They added some protection, updated
