### ISSUE TITLE
Line Errors

### ISSUE THREAD

**Issue by nuketownhf** [enjoy2000/discord-pokemon-go-snipe-bot#51]
http://i.imgur.com/lxPjqn4.png

C:\discord-pokemon-go-snipe-bot>python bot.py
Traceback (most recent call last):
  File "bot.py", line 27, in <module>
    config = json.load(output)
  File "C:\Python352\lib\json__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Python352\lib\json__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\Python352\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python352\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 6 column 2 (char 110)
Exception ignored in: <bound method ClientSession.__del__ of <aiohttp.client.ClientSession object at 0x02F94EB0>>
Traceback (most recent call last):
  File "C:\Python352\lib\site-packages\aiohttp\client.py", line 91, in **del**
  File "C:\Python352\lib\asyncio\base_events.py", line 1177, in call_exception_handler
  File "C:\Python352\lib\logging__init__.py", line 1308, in error
  File "C:\Python352\lib\logging__init__.py", line 1415, in _log
  File "C:\Python352\lib\logging__init__.py", line 1425, in handle
  File "C:\Python352\lib\logging__init__.py", line 1487, in callHandlers
  File "C:\Python352\lib\logging__init__.py", line 855, in handle
  File "C:\Python352\lib\logging__init__.py", line 1047, in emit
  File "C:\Python352\lib\logging__init__.py", line 1037, in _open
NameError: name 'open' is not defined

**Comment by enjoy2000** [comment]
Check your `config.json`, wrong syntax I guess

**Comment by nuketownhf** [comment]
There was everything well configured, shall I take a screenshot?
