### ISSUE TITLE
trackmon doesn't work.

### ISSUE THREAD

**Issue by wpark6765** [enjoy2000/discord-pokemon-go-snipe-bot#65]
your trackmon doesn't show any outputs

**Comment by Navyguy330** [comment]
C:\Scrawler>python bot.py trackemon
[04:15:33]  Logged in as
[04:15:33]  SnipeBot-90
[04:15:33]  209425950109073409
[04:15:33]  ------

**Comment by Navyguy330** [comment]
just hangs there

**Comment by Navyguy330** [comment]
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<scrawl_trackemon_worker() done, defined at C:\Scrawler\bot.py:186> exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)',)>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Scrawler\bot.py", line 209, in scrawl_trackemon_worker
    message = scrawl_trackemon(pokemon_name, session_data)
  File "C:\Scrawler\bot.py", line 101, in scrawl_trackemon
    data = response.json()
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\requests\models.py", line 812, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Program Files (x86)\Python35-32\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files (x86)\Python35-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files (x86)\Python35-32\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<scrawl_trackemon_worker() done, defined at bot.py:186> exception=HTTPException('BAD REQUEST (status code: 400)',)>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "bot.py", line 213, in scrawl_trackemon_worker
    await client.send_message(channel, message)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\discord\client.py", line 824, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\discord\http.py", line 137, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: BAD REQUEST (status code: 400)
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<scrawl_trackemon_worker() done, defined at bot.py:186> exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)',)>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "bot.py", line 209, in scrawl_trackemon_worker
    message = scrawl_trackemon(pokemon_name, session_data)
  File "bot.py", line 101, in scrawl_trackemon
    data = response.json()
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\requests\models.py", line 812, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Program Files (x86)\Python35-32\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files (x86)\Python35-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files (x86)\Python35-32\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<scrawl_trackemon_worker() done, defined at bot.py:205> exception=Exception('No channel to shout out!',)>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "bot.py", line 217, in scrawl_trackemon_worker
    raise Exception("No channel to shout out!")
Exception: No channel to shout out!
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<scrawl_trackemon_worker() done, defined at bot.py:205> exception=Exception('No channel to shout out!',)>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "bot.py", line 217, in scrawl_trackemon_worker
    raise Exception("No channel to shout out!")
Exception: No channel to shout out!
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<scrawl_trackemon_worker() done, defined at bot.py:205> exception=Exception('No channel to shout out!',)>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "bot.py", line 217, in scrawl_trackemon_worker
    raise Exception("No channel to shout out!")
Exception: No channel to shout out!
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<scrawl_trackemon_worker() done, defined at bot.py:205> exception=Exception('No channel to shout out!',)>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "bot.py", line 217, in scrawl_trackemon_worker
    raise Exception("No channel to shout out!")
Exception: No channel to shout out!

**Comment by Navyguy330** [comment]
Fixed someone changed the channel name on me

**Comment by wpark6765** [comment]
@enjoy2000 trackmon doesn't show any outputs.
