### ISSUE TITLE
Help please 

### ISSUE THREAD

**Issue by Azndee2** [enjoy2000/discord-pokemon-go-snipe-bot#67]
C:\Users\Jason>cd C:\

C:>cd C:\Users\Jason\discord-pokemon-go-snipe-bot-master

C:\Users\Jason\discord-pokemon-go-snipe-bot-master>Bot.py
Traceback (most recent call last):
  File "C:\Users\Jason\discord-pokemon-go-snipe-bot-master\bot.py", line 31, in <module>
    config = json.load(output)
  File "C:\python35.2\lib\json__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\python35.2\lib\json__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\python35.2\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\python35.2\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 2 (char 114)
Exception ignored in: <bound method ClientSession.__del__ of <aiohttp.client.ClientSession object at 0x0000021ECE3715C0>>
Traceback (most recent call last):
  File "C:\python35.2\lib\site-packages\aiohttp\client.py", line 91, in **del**
  File "C:\python35.2\lib\asyncio\base_events.py", line 1177, in call_exception_handler
  File "C:\python35.2\lib\logging__init__.py", line 1308, in error
  File "C:\python35.2\lib\logging__init__.py", line 1415, in _log
  File "C:\python35.2\lib\logging__init__.py", line 1425, in handle
  File "C:\python35.2\lib\logging__init__.py", line 1487, in callHandlers
  File "C:\python35.2\lib\logging__init__.py", line 855, in handle
  File "C:\python35.2\lib\logging__init__.py", line 1047, in emit
  File "C:\python35.2\lib\logging__init__.py", line 1037, in _open
NameError: name 'open' is not defined

C:\Users\Jason\discord-pokemon-go-snipe-bot-master>Python Bot.py
Traceback (most recent call last):
  File "Bot.py", line 31, in <module>
    config = json.load(output)
  File "C:\python35.2\lib\json__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\python35.2\lib\json__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\python35.2\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\python35.2\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 2 (char 114)
Exception ignored in: <bound method ClientSession.__del__ of <aiohttp.client.ClientSession object at 0x000001407CD9F668>>
Traceback (most recent call last):
  File "C:\python35.2\lib\site-packages\aiohttp\client.py", line 91, in **del**
  File "C:\python35.2\lib\asyncio\base_events.py", line 1177, in call_exception_handler
  File "C:\python35.2\lib\logging__init__.py", line 1308, in error
  File "C:\python35.2\lib\logging__init__.py", line 1415, in _log
  File "C:\python35.2\lib\logging__init__.py", line 1425, in handle
  File "C:\python35.2\lib\logging__init__.py", line 1487, in callHandlers
  File "C:\python35.2\lib\logging__init__.py", line 855, in handle
  File "C:\python35.2\lib\logging__init__.py", line 1047, in emit
  File "C:\python35.2\lib\logging__init__.py", line 1037, in _open
NameError: name 'open' is not defined

C:\Users\Jason\discord-pokemon-go-snipe-bot-master>

idk where i went wrong.

**Comment by enjoy2000** [comment]
Missing `config.json` I guess.

Did u follow all my commands?

**Comment by Azndee2** [comment]
yea

**Comment by Azndee2** [comment]
i copy and pasted the config.json.sample and renamed the pasted to config.json

**Comment by Azndee2** [comment]
what i have in my folder rn https://gyazo.com/89e44174442ac79ac95934d0c8d270b7

**Comment by enjoy2000** [comment]
Check json syntax on config.js

**Comment by Azndee2** [comment]
https://gyazo.com/0a2073ac2a7eec22766936e8163f6e73 thats whats in my config file
