### ISSUE TITLE
Api is busy with Trackemon

### ISSUE THREAD

**Issue by itsDustinBerry** [enjoy2000/discord-pokemon-go-snipe-bot#72]
When using Trackemon with the newest update, It sometimes will skip over pokemon and in the command window it says "API is busy" and completely skips over the given pokemon.

**Comment by Azndee2** [comment]
hows trackemon working for u it dosnt show any pokemon for me

**Comment by itsDustinBerry** [comment]
Sometimes it is saying "There is some error... red"

In the messages log, I get this:

ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending coro=<scrawl_trackemon_worker() running at bot.py:241> wait_for=<Future pending cb=[Task._wakeup(), BaseSelectorEventLoop._sock_connect_done(844)()]>>

**Comment by itsDustinBerry** [comment]
Also, Getting this message:

ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending coro=<scrawl_trackemon_worker() running at bot.py:241> wait_for=<Future pending cb=[Task._wakeup(), BaseSelectorEventLoop._sock_connect_done(844)()]>>
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<get_rare_pokemons() done, defined at bot.py:162> exception=HTTPException('BAD REQUEST (status code: 400): Cannot send an empty message',)>
Traceback (most recent call last):
  File "C:\Users\My\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "bot.py", line 193, in get_rare_pokemons
    await client.send_message(channel, message)
  File "C:\Users\My\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 825, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts)
  File "C:\Users\My\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\http.py", line 137, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: BAD REQUEST (status code: 400): Cannot send an empty message
ERROR:concurrent.futures:exception calling callback for <Future at 0x91ac830 state=finished returned list>
Traceback (most recent call last):
  File "C:\Users\My\AppData\Local\Programs\Python\Python35-32\lib\concurrent\futures_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "C:\Users\My\AppData\Local\Programs\Python\Python35-32\lib\asyncio\futures.py", line 442, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "C:\Users\My\AppData\Local\Programs\Python\Python35-32\lib\asyncio\base_events.py", line 532, in call_soon_threadsafe
    handle = self._call_soon(callback, args)
  File "C:\Users\My\AppData\Local\Programs\Python\Python35-32\lib\asyncio\base_events.py", line 506, in _call_soon
    self._check_closed()
  File "C:\Users\My\AppData\Local\Programs\Python\Python35-32\lib\asyncio\base_events.py", line 334, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending coro=<scrawl_trackemon_worker() running at bot.py:241> wait_for=<Future pending cb=[Task._wakeup()]>>

**Comment by MajorChump** [comment]
Hi guys,

The reason its not working is I have to keep reshuffling it. The site is being overloaded by 3rd party tools and traffic from 3rd party is about 10x that of normal traffic. I wish I could support your project but I can't support the level of traffic its bringing to the site. I would very much appreciate if you could find an alternative.

Thanks.

**Comment by itsDustinBerry** [comment]
-sadface-
