### ISSUE TITLE
Latest Update Error

### ISSUE THREAD

**Issue by realjesset** [enjoy2000/discord-pokemon-go-snipe-bot#73]
Traceback (most recent call last):
  File "bot.py", line 27, in <module>
    config = json.load(output)
  File "C:\Users\thego\AppData\Local\Programs\Python\Python35\lib\json__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\thego\AppData\Local\Programs\Python\Python35\lib\json__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\Users\thego\AppData\Local\Programs\Python\Python35\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\thego\AppData\Local\Programs\Python\Python35\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 24 column 9 (char 518)
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000025C5F4699E8>

I got this error when I updated the bot and ran this

**Comment by enjoy2000** [comment]
I have FAQ section in readme.

Use some tool online to check your `json syntax`
