### ISSUE TITLE
Not deleting blacklist

### ISSUE THREAD

**Issue by realjesset** [enjoy2000/discord-pokemon-go-snipe-bot#77]
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\thego\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(_args, *_kwargs)
  File "C:\Users\thego\Desktop\Pokemon GO\Discord Bot\discord-pokemon-go-snipe-bot\bot.py", line 46, in on_message
    if bot.on_message(message):
  File "C:\Users\thego\Desktop\Pokemon GO\Discord Bot\discord-pokemon-go-snipe-bot\snipe_bot__init__.py", line 47, in on_message
    return worker.need_to_delete(message)
  File "C:\Users\thego\Desktop\Pokemon GO\Discord Bot\discord-pokemon-go-snipe-bot\snipe_bot\workers\channel_management.py", line 69, in need_to_delete
    if not (re.match(pattern, message.content) or re.match(reverse_pattern, message.content)) or self._is_blacklisted(message.content):
TypeError: _is_blacklisted() takes 1 positional argument but 2 were given

Having that error, even tho my config looks like this http://pastebin.com/evA6wuZr

**Comment by enjoy2000** [comment]
fixed, thanks

**Comment by realjesset** [comment]
yup thnx
